<?php
$customer = $this->getCustomerInformation();
?>
<div class="fieldset-wrapper customer-information">
    <legend class="admin__legend legend">
        <span><?= $block->escapeHtml(__('Customer Information')) ?></span>:
        <span><a href="<?= $this->getCustomerUrl($this->getCustomerInformation()->getId()) ?>"><?= $block->escapeHtml(__('View')) ?></a></span>
    </legend >
    <table class="admin__table-secondary">
        <tbody>
        <tr>
            <th><?= $block->escapeHtml(__('First Name')) ?></th>
            <td><?= $customer->getData('firstname') ?></td>
        </tr>
        <tr>
            <th><?= $block->escapeHtml(__('Middle Name')) ?></th>
            <td><?= $customer->getData('middlename') ?></td>
        </tr>
        <tr>
            <th><?= $block->escapeHtml(__('Last Name')) ?></th>
            <td><?= $customer->getData('lastname') ?></td>
        </tr>
        </tbody>
    </table>
</div>