<div class="fieldset-wrapper customer-information">
    <legend class="admin__legend legend">
        <span><?= $block->escapeHtml(__('Customer Information')) ?></span>
    </legend >
    <table class="admin__table-secondary">
        <tbody>
        <tr>
            <th><?= $block->escapeHtml(__('First Name')) ?></th>
        </tr>
        <tr>
            <th><?= $block->escapeHtml(__('Last Name')) ?></th>
        </tr>
        </tbody>
    </table>
</div>